### ISSUE TITLE
"end" event isn't fired

### ISSUE THREAD

**Issue by hughsk** [nfroidure/gulp-streamify#2]
Just a heads up: this stops streams being piped to from gulp-streamify from ending, e.g. stopping gulp-size and similar plugins from working correctly:

``` javascript
var streamify = require('gulp-streamify')
var uglify = require('gulp-uglify')
var size = require('gulp-size')
var gulp = require('gulp')

gulp.task('build', function() {
  gulp.src('*.js', { buffer: false })
    .pipe(streamify(uglify()))
    .pipe(size()) // never reports size
    .pipe(gulp.dest('dist/'))
})
```

**Comment by nfroidure** [comment]
Abandonning v0.8 streams support since it is painful and i suppose old plugins should be updated or not used.
