### ISSUE TITLE
Trouble using multiple streams inside one streamify call

### ISSUE THREAD

**Issue by AgentME** [nfroidure/gulp-streamify#5]
The gulp-streamify documentation claims you can chain multiple streams from inside one streamify call:

```javascript
gulp.task('stream', function(){
  gulp.src(['**/*'])
    .pipe(gStreamify(
      noStreamPlugin().pipe(noStreamPlugin2())
    ))
    .pipe(gulp.dest('/tmp'));
});
```

I'm having trouble getting this to work. See https://github.com/AgentME/gulp-building-test for a gulpfile with two tasks, "good" and "bad". Each task takes a stream from Browserify, pipes it to gulp-sourcemaps.init to parse the sourcemaps, through uglify to minify it, and then to gulp-sourcemaps.write('.') to write the sourcemap to an external file. The "good" task uses a separate streamify call per stream, and the "bad" task uses one streamify call. The "bad" task fails to minify or write any external sourcemaps.

I originally reported this issue against gulp-concat before I realized it wasn't specific to that plugin: https://github.com/wearefractal/gulp-concat/issues/93

**Comment by nfroidure** [comment]
You must use the function form of gulp streamify to do this in combination with a duplexer this one: https://www.npmjs.com/package/plexer

You example would become:
```js
gulp.task('stream', function(){
  gulp.src(['**/*'])
    .pipe(gStreamify(function() {
      var instream = noStreamPlugin();
      var outstream = noStreamPlugin2();
      instream
        .pipe(anyOtherStream)
        .pipe(outStream);
      return plexer(instream, outstream);
    }))
    .pipe(gulp.dest('/tmp'));
});
```

You can also look at multipipe.

**Comment by AgentME** [comment]
The readme should be fixed to not have that example.

**Comment by nfroidure** [comment]
I'm actually doing so ;)
